### ISSUE TITLE
Gettting error while try to import basic functions

### ISSUE THREAD

**Issue by Dhamu143** [ConsenSys/infura-sdk#93] opened 2022-09-26 10:44 UTC
![Selection_150](https://user-images.githubusercontent.com/20680578/192257224-41674b47-0674-41e4-b08b-4366d97cf70d.png)

I am getting this error while trying to use the **@infura/sdk**  

If i try to use this in package.json to resolve this error **"type": "module"** , my other code is getting affected.

**Comment by salimtb** [comment] 2022-12-07 13:25
hey @Dhamu143 , 
the problem is now fixed, the commonJS import is now supported

**Closed by salimtb** 2022-12-07 13:25 UTC
